'use strict';

// Unit test for the entrypoint: verifies the yt-dlp config generated by the
// container contains the critical production lines (without running the
// script, just its content). Prevents regressions of the RD radio fix
// (--playlist-end) and the bot-check workaround (player_client=android).

const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const ENTRYPOINT = path.join(__dirname, '..', 'entrypoint.sh');
const source = fs.readFileSync(ENTRYPOINT, 'utf8');

test('entrypoint.sh generates a yt-dlp config with --js-runtimes node', () => {
  assert.match(source, /--js-runtimes node/);
});

test('entrypoint.sh uses player_client=android to evade the bot-check', () => {
  assert.match(source, /--extractor-args youtube:player_client=android/);
});

test('entrypoint.sh limits playlists to 15 songs (RD radio fix)', () => {
  assert.match(source, /--playlist-end 15/);
});

test('entrypoint.sh only enables cookies if it is a non-empty regular file', () => {
  // `-f` (regular file) is critical: in a fresh deploy without cookies.txt,
  // Docker mounts a DIRECTORY and `test -s` passes against directories (st_size 4096),
  // which would make yt-dlp fail reading a directory as a cookies file.
  assert.match(source, /-f \/app\/cookies\.txt/);
  assert.match(source, /-s \/app\/cookies\.txt/);
  assert.match(source, /--cookies \/app\/cookies\.txt/);
});
